// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeKJMGGgZhn80S920zEf5zqCjjtqsBciE',
    appId: '1:306841653586:web:bfb02054926729f379aa8b',
    messagingSenderId: '306841653586',
    projectId: 'ifpi-d2ed7',
    authDomain: 'ifpi-d2ed7.firebaseapp.com',
    storageBucket: 'ifpi-d2ed7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNB9OaxKsOgCFUeB9fUMwKi0BZdLvbkFU',
    appId: '1:306841653586:android:9f6368ab83d60d7b79aa8b',
    messagingSenderId: '306841653586',
    projectId: 'ifpi-d2ed7',
    storageBucket: 'ifpi-d2ed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs9WFsqFkaRAOp341m-S_6tyZnCYAOh7I',
    appId: '1:306841653586:ios:12d6ff4cab09b34e79aa8b',
    messagingSenderId: '306841653586',
    projectId: 'ifpi-d2ed7',
    storageBucket: 'ifpi-d2ed7.appspot.com',
    iosClientId: '306841653586-v5b8ocm29nr628912cb59u1uteoce49k.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDeContatos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs9WFsqFkaRAOp341m-S_6tyZnCYAOh7I',
    appId: '1:306841653586:ios:12d6ff4cab09b34e79aa8b',
    messagingSenderId: '306841653586',
    projectId: 'ifpi-d2ed7',
    storageBucket: 'ifpi-d2ed7.appspot.com',
    iosClientId: '306841653586-v5b8ocm29nr628912cb59u1uteoce49k.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDeContatos',
  );
}
